version: "3.8"

services:
  ros-noetic:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_UID=1000
        - CUSTOM_GID=1000
    container_name: ros_noetic
    network_mode: host
    ipc: host
    privileged: true
    tty: true
    stdin_open: true

    environment:
      - QT_GRAPHICSSYSTEM=native
      - DISPLAY=unix${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DISTRO=noetic

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ${PWD}/..:/home/noetic/fast_calib_ws
      - ${HOME}/rosbags:/home/noetic/rosbags
